Parameters:
  InstanceType:
    Type: String
    Description: "EC2 instance type"
    AllowedValues:
       - t2.micro
       - t2.nano
       - t2.small
    Default: t2.micro

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-0c50b6f7dc3701ddd
